extension:
  - ts
spec: 
  - test/**/*.node.test.ts
  # - test/runtime-variables/EvalFunctions.node.test.ts
require: 
  - ts-node/register
  - source-map-support/register.js
  - test/http-server-fixture.ts
loader: ts-node/esm
watch-files:
  - src
  - test
watch-ignore:
  - test/express.lock
timeout: 20000
