extension:
  - ts
spec: 
  - test/**/*.node.test.ts
  # - test/reporters/ProjectRunCliReporter.node.test.ts
require: ts-node/register
loader: ts-node/esm
watch-files:
  - src
  - test
watch-ignore:
  - test/express.lock
timeout: 20000
