#%Dialect 1.0

dialect: Environment
version: 1.0

uses:
  Thing: Thing.yaml
  Server: Server.yaml
  Property: Property.yaml
  ApiProject: ApiProjectVocabulary.yaml

documents:
  root:
    encodes: EnvironmentNode

nodeMappings:
  EnvironmentNode:
    classTerm: ApiProject.Environment
    mapping:
      kind:
        range: string
        mandatory: true
      key:
        range: string
        mandatory: true
      encapsulated:
        range: boolean
        mandatory: false
      info:
        range: Thing.ThingNode
        mandatory: true
      server:
        range: Server.ServerNode
        mandatory: false
      variables:
        range: Property.PropertyNode
        allowMultiple: true
        mandatory: false
